# Kích thước màn hình
GRID_SIZE = 20
GRID_WIDTH = 30
GRID_HEIGHT = 25

SCREEN_WIDTH = GRID_SIZE * GRID_WIDTH
SCREEN_HEIGHT = GRID_SIZE * GRID_HEIGHT

# Màu sắc
COLOR_BACKGROUND = (0, 0, 0)
COLOR_FOOD = (255, 0, 0)
COLOR_GRID = (40, 40, 40)
COLOR_TEXT = (255, 255, 255)

# Cấu hình Game
BASE_SPEED = 8

# Cấu hình Save
SAVE_DIR = "saves"
SAVE_FILE_EXTENSION = ".json"